### PR TITLE
Restaurant page built with ES6 modules, using webpack.

### PR DESCRIPTION
**Pull request by MkrtichSargsyan**
created simple restaurant webpage with the use of a web pack

Built With

HTML,
CSS,
VS Code
JavaScript
Tailwind.css
Webpack

### CODE REVIEW

**Review by trekab — CHANGES_REQUESTED** [review]
### Changes Required! :recycle: 
Well done working on the suggested change from the [Last Review](https://github.com/MkrtichSargsyan/Restaurant-Page/pull/3), @MkrtichSargsyan! However, there are some changes you need to consider before having this project approved. These include:

- [x] Your implementation of the tabbed menu is different from the feature description. The tabbed menu should stay on the page while the page content changes with a click on the different menu links. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/restaurant_page/tab_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/restaurant-page))
- [x] __[Note]__ Please don't merge or close unapproved pull requests. Try to maintain the same pull request for all code reviews for a given project.

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[Portfolio](https://trekab.github.io/portfolio/) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

**Comment by MkrtichSargsyan** [comment]
I already have tabs on index.js,you need to scroll down until the menu section so they become visible.

**Review by peterrobert — CHANGES_REQUESTED** [review]
### CHANGES REQUIRED ♻️ 🛑 
Hello, @MkrtichSargsyan very nice project. I love your codebase, good work using webpack as requested. However, there seem to be a few issues that need to be addressed kindly check the following:

- [x] There seems to be an error when I run your project locally. Kindly check below ⬇️ 

Screenshot from 2021-02-11 07-42-29

- [x]  When I use the live version to check your work, there seems to be a problem with your tabbed menu. Am only able to navigate to two pages, the menu page, and the home page. Navigation to your contact page doesn't seem to work. Kindly fix that. ⬇️ 

tab_requirement

- [ ] Kindly remember to always capitalize your commit messages. When doing your commits, kindly try and follow these best practices. [article](https://github.com/trein/dev-best-practices/wiki/Git-Commit-Best-Practices#formatting-rules)

### if you have any question, kindly reach me via slack @peterrobert

### HAPPY CODING 💻

**Review by bellom — APPROVED** [review]
## Hi @MkrtichSargsyan  :clap: 

**Great work making all the necessary corrections from the previous review.**

**Kindly update your live link before merging.**

# Status: Approved 👍 

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit the project completion form.
Good luck in the next project :slightly_smiling_face:_ 

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

**Pull request merged**
